"""empty message

Revision ID: fcc50ed652ec
Revises: 96700d4d0aea
Create Date: 2025-07-16 10:15:42.587377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc50ed652ec'
down_revision = '96700d4d0aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column(
            'booking_date',
            existing_type=sa.VARCHAR(),
            type_=sa.Date(),
            existing_nullable=False,
            postgresql_using='booking_date::date'  # <-- esta línea es la clave
        )

    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.alter_column(
            'departure_date',
            existing_type=sa.VARCHAR(),
            type_=sa.Date(),
            existing_nullable=False,
            postgresql_using='departure_date::date'
        )
        batch_op.alter_column(
            'arrive_date',
            existing_type=sa.VARCHAR(),
            type_=sa.Date(),
            existing_nullable=False,
            postgresql_using='arrive_date::date'
        )
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.alter_column('arrive_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('departure_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('booking_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
